### ISSUE TITLE
exit signal Segmentation fault (11)

### ISSUE THREAD

**Issue by PreDeToR** [PerimeterX/mod_perimeterx#124]
Hi Guys

I am trying to setup perimeterx on only one of the multiple domains I run on my box, however it seems because I do not have a perimeterx config for the other domains, it causes my apache to segfault.

Is there a way to by default "disable" the module and only enable it for the one virtual domain?

Regards
Danie

**Comment by bendpx** [comment]
Hey Danie, 

Thanks for reporting. 

can you please share the config you're trying to work with to my email - ben@perimeterx.com and we'll address to it?

Thanks,
Ben

**Comment by nitzanpx** [comment]
Danie,
Thank you for reporting this issue, we have fixed it on v2.10.1
